image: docker:latest

variables:
  IMAGE_HOST: docker.lan:444
  IMAGE_NAME: petris/hdhr-proxy:latest

stages:
  - build

before_script:
  - docker info
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$IMAGE_HOST"

build:
  stage: build
  tags:
    - docker
  script:
    - docker build --no-cache --pull --tag "${IMAGE_HOST}/${IMAGE_NAME}" .
    - docker push "${IMAGE_HOST}/${IMAGE_NAME}"
